export default {
  LOAD_POSTS: 'LOAD_POSTS',
  LOAD_POSTS_SUCCESS: 'LOAD_POSTS_SUCCESS',
  LOAD_POSTS_FAIL: 'LOAD_POSTS_FAIL',

  LOAD_POST: 'LOAD_POST',
  LOAD_POST_SUCCESS: 'LOAD_POST_SUCCESS',
  LOAD_POST_FAIL: 'LOAD_POST_FAIL',

  LOAD_POST_COMMENTS: 'LOAD_POST_COMMENTS',
  LOAD_POST_COMMENTS_SUCCESS: 'LOAD_POST_COMMENTS_SUCCESS',
  LOAD_POST_COMMENTS_FAIL: 'LOAD_POST_COMMENTS_FAIL',

  NEW_POST_COMMENT: 'NEW_POST_COMMENT',
  NEW_POST_COMMENT_SUCCESS: 'NEW_POST_COMMENT_SUCCESS',
  NEW_POST_COMMENT_FAIL: 'NEW_POST_COMMENT_FAIL'
}
