import keyMirror from 'keymirror'

export default keyMirror({
  LOAD_IMAGES: null,
  LOAD_IMAGES_SUCCESS: null,
  LOAD_IMAGES_FAIL: null,

  LOAD_IMAGES_BYTAG: null,
  LOAD_IMAGES_BYTAG_SUCCESS: null,
  LOAD_IMAGES_BYTAG_FAIL: null,

  LOAD_IMAGE_BYID: null,
  LOAD_IMAGE_BYID_SUCCESS: null,
  LOAD_IMAGE_BYID_FAIL: null,

  LOAD_IMAGE_BYFILENAME: null,
  LOAD_IMAGE_BYFILENAME_SUCCESS: null,
  LOAD_IMAGE_BYFILENAME_FAIL: null,

  LOAD_POST_COMMENTS: null,
  LOAD_POST_COMMENTS_SUCCESS: null,
  LOAD_POST_COMMENTS_FAIL: null,

  NEW_POST_COMMENT: null,
  NEW_POST_COMMENT_SUCCESS: null,
  NEW_POST_COMMENT_FAIL: null
})
